In [15]:
import numpy as np

t_initial = 0
t_end = 10  # Time span (s)
dt = 0.1  # Time step


Kp = np.array([[2, 0], [0, 1]])
Kd = np.array([[2, 0], [0, 1]])
state = np.array([[2],[3],[4],[0]])
goal_position = np.array([[5],[5]])
t_range = np.arange(0, t_end + dt, dt)
n_states = int((t_end - t_initial)/dt)
state_list = np.zeros((4, n_states))
state_list.shape
state.shape


(4, 1)

In [16]:
state

array([[2],
       [3],
       [4],
       [0]])

In [18]:
state_list[:,0] = state

ValueError: could not broadcast input array from shape (4,1) into shape (4,)

In [14]:
state_list[:,0]

array([0., 0., 0., 0.])

In [39]:
state = np.array([[0],[0],[0],[0]])
print(state)

[[0]
 [0]
 [0]
 [0]]


In [41]:
state[2,0]

0

In [43]:
state_new = np.zeros_like(state)
print(state_new)
state_new[0,0]

[[0]
 [0]
 [0]
 [0]]


0

In [28]:
state[3]
u = [[0],[0]]
state_new = np.zeros_like(state)


In [38]:
state_new[0,0] = state[0,0]+state[2,0]*dt+0.5*u[0,0]*dt**2

TypeError: list indices must be integers or slices, not tuple